# Проверки, которые запускаются перед каждым коммитом
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Линтер с автоисправлением
      - id: ruff
        args: [--fix]
      # Форматировщик кода
      - id: ruff-format