"""add icon to categories

Revision ID: 12b07c56b124
Revises: afbc64d63b77
Create Date: 2026-06-21 19:03:06.861749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12b07c56b124"
down_revision: Union[str, Sequence[str], None] = "afbc64d63b77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("icon", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "icon")
    # ### end Alembic commands ###
