"""add material and care to product

Revision ID: 13b89dac497d
Revises: c7f5d00b3ee2
Create Date: 2026-06-26 10:15:48.174316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13b89dac497d"
down_revision: Union[str, Sequence[str], None] = "c7f5d00b3ee2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("material", sa.String(length=255), nullable=True)
    )
    op.add_column("products", sa.Column("care", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "care")
    op.drop_column("products", "material")
    # ### end Alembic commands ###
