"""Add payment_external_id to return_requests

Revision ID: 63a0e352598e
Revises: 3c1e4edaac09
Create Date: 2026-06-23 08:11:17.506625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63a0e352598e"
down_revision: Union[str, Sequence[str], None] = "3c1e4edaac09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("payment_external_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_external_id")
    # ### end Alembic commands ###
