"""add icon to categories

Revision ID: 77bf0db6a3ed
Revises: 12b07c56b124
Create Date: 2026-06-21 19:05:28.223365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77bf0db6a3ed"
down_revision: Union[str, Sequence[str], None] = "12b07c56b124"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("icon", sa.String(length=64), nullable=True))
    op.drop_column("products", "icon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("icon", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.drop_column("categories", "icon")
    # ### end Alembic commands ###
