"""add badge to products

Revision ID: 78e747e4e2c1
Revises: cfa58c0b066f
Create Date: 2026-06-20 22:49:46.831022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78e747e4e2c1"
down_revision: Union[str, Sequence[str], None] = "cfa58c0b066f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("badge", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "badge")
    # ### end Alembic commands ###
