"""add cdek delivery fields to orders

Revision ID: 7f79b3ed6788
Revises: 476f62be747b
Create Date: 2026-06-28 14:43:07.272300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f79b3ed6788"
down_revision: Union[str, Sequence[str], None] = "476f62be747b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("delivery_type", sa.String(length=16), nullable=False)
    )
    op.add_column("orders", sa.Column("cdek_city_code", sa.Integer(), nullable=True))
    op.add_column(
        "orders", sa.Column("cdek_city_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("cdek_pvz_code", sa.String(length=32), nullable=True)
    )
    op.add_column("orders", sa.Column("cdek_pvz_address", sa.Text(), nullable=True))
    op.add_column(
        "orders", sa.Column("cdek_order_uuid", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("cdek_track_number", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "cdek_track_number")
    op.drop_column("orders", "cdek_order_uuid")
    op.drop_column("orders", "cdek_pvz_address")
    op.drop_column("orders", "cdek_pvz_code")
    op.drop_column("orders", "cdek_city_name")
    op.drop_column("orders", "cdek_city_code")
    op.drop_column("orders", "delivery_type")
    # ### end Alembic commands ###
