"""Add payment_external_id to return_requests

Revision ID: 857a76603dd4
Revises: 63a0e352598e
Create Date: 2026-06-23 08:14:25.938087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "857a76603dd4"
down_revision: Union[str, Sequence[str], None] = "63a0e352598e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_external_id")
    op.add_column(
        "return_requests",
        sa.Column("payment_external_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("return_requests", "payment_external_id")
    op.add_column(
        "payments",
        sa.Column(
            "payment_external_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
