"""rename old_price to sale_price

Revision ID: 867cb6badf91
Revises: bdf5f96ecdb9
Create Date: 2026-06-21 19:39:43.363179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867cb6badf91'
down_revision: Union[str, Sequence[str], None] = 'bdf5f96ecdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('products', 'old_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('old_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('products', 'sale_price')
    # ### end Alembic commands ###
