"""add weight to product and order_item

Revision ID: a5d60e97e02c
Revises: 7f79b3ed6788
Create Date: 2026-06-28 20:37:00.956335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5d60e97e02c"
down_revision: Union[str, Sequence[str], None] = "7f79b3ed6788"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "order_items",
        sa.Column("weight", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "products",
        sa.Column("weight", sa.Integer(), nullable=False, server_default="0"),
    )
    # убираем server_default — в коде значение обязательное, дефолт только для миграции
    op.alter_column("order_items", "weight", server_default=None)
    op.alter_column("products", "weight", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "weight")
    op.drop_column("order_items", "weight")
    # ### end Alembic commands ###
