"""add product_image to order items

Revision ID: afbc64d63b77
Revises: 78e747e4e2c1
Create Date: 2026-06-21 18:23:35.046087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afbc64d63b77"
down_revision: Union[str, Sequence[str], None] = "78e747e4e2c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("product_image", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "product_image")
    # ### end Alembic commands ###
