"""add old_price to products

Revision ID: bdf5f96ecdb9
Revises: 77bf0db6a3ed
Create Date: 2026-06-21 19:35:36.626691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdf5f96ecdb9"
down_revision: Union[str, Sequence[str], None] = "77bf0db6a3ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("old_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "old_price")
    # ### end Alembic commands ###
