"""add variant_id and size to order_items

Revision ID: c5471e29391b
Revises: 7e9eb431e3bb
Create Date: 2026-06-20 09:51:37.253648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5471e29391b"
down_revision: Union[str, Sequence[str], None] = "7e9eb431e3bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("variant_id", sa.UUID(), nullable=True))
    op.add_column("order_items", sa.Column("size", sa.String(length=32), nullable=True))
    op.create_foreign_key(
        None, "order_items", "product_variants", ["variant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_items", type_="foreignkey")
    op.drop_column("order_items", "size")
    op.drop_column("order_items", "variant_id")
    # ### end Alembic commands ###
