"""add gender to product

Revision ID: ca8022c22f99
Revises: db6744eb2eb8
Create Date: 2026-06-27 09:05:51.006992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca8022c22f99"
down_revision: Union[str, Sequence[str], None] = "db6744eb2eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("gender", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "gender")
    # ### end Alembic commands ###
